<a href="https://colab.research.google.com/github/juanpajedrez/tensorflow_learning/blob/main/Notebook_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Important functions tensorflow
This jupyter notebook contains some of the most common used tensorflow functions that can be used for performing important tasks.

In [1]:
import tensorflow as tf

In [2]:
# Lets simulate a tensor 3D
tensor_three_d = tf.constant([[[1, 2, 0],
                              [3, 5, -1]],

                             [[10, 2, 0],
                              [1, 0, 2]],

                             [[5, 8, 0],
                              [2, 7, 0]],

                             [[2, 1, 9],
                              [4, 3, 32]]])

#Lets see the shape
print(tensor_three_d.shape)

(4, 2, 3)


### tensorflow: expand dimension

lets see its effects on 1D, 2D and 3D tensors

In [3]:
#Showcasing how to expand dimensions
print(tf.expand_dims(tensor_three_d, axis = 0).shape)

(1, 4, 2, 3)


In [4]:
#Lets see the effect on a 1D tensorflow array shape
x = tf.constant([2, 3, 4, 5])

#Lets see the shapes
print(x.shape)
print(tf.expand_dims(x, axis = 0).shape)

(4,)
(1, 4)


In [5]:
#Showcasing how to expand dimensions from 3D to 4D dimensions
print(tensor_three_d.shape)
print(tf.expand_dims(tensor_three_d, axis = 1).shape)

(4, 2, 3)
(4, 1, 2, 3)


### tensorflow: squeeze method
Lets see the opposite of expand_dimensions! this is the squeeze method

In [6]:
#Lets see the effects on small example
x = tf.constant([[[[2, 3, 4, 5]]]])
print(x.shape)
x_expanded = tf.squeeze(x, axis = 0)
print(x_expanded.shape)

(1, 1, 1, 4)
(1, 1, 4)


In [7]:
for i in range(2):
  # Get the shapes as you keep squeezing in the first dim
  x_squeezed = tf.squeeze(x_expanded, axis = 0)
  print(x_squeezed.shape)

  #Update the x_expanded
  x_expanded = x_squeezed

(1, 4)
(4,)


In [8]:
# Lets see squeeze for 3D tensors
tensor_three_d = tf.constant([[[1, 2, 0],
                              [3, 5, -1]],

                             [[10, 2, 0],
                              [1, 0, 2]],

                             [[5, 8, 0],
                              [2, 7, 0]],

                             [[2, 1, 9],
                              [4, 3, 32]]])

#Lets see the shape
print(tensor_three_d.shape)

(4, 2, 3)


In [9]:
# Lets expand dimensions for the last dim
x_exp = tf.expand_dims(tensor_three_d, axis = 3)
print(x_exp.shape)

#Now lets see the effect of squeeze in third axis
print(tf.squeeze(x_exp, axis = 3).shape)

(4, 2, 3, 1)
(4, 2, 3)


### tensorflow: reshape method
This is a mostly used method for reshaping tensors; lets take a look!

In [10]:
# Continuing from the previous x_exp, lets see the effects of reshape
print(tf.reshape(x_exp, [4, 2, 3]).shape)

(4, 2, 3)


In [11]:
# Lets check if the outputs are the same
tf.reshape(x_exp, [4, 2, 3]) == tf.squeeze(x_exp, axis = 3)

<tf.Tensor: shape=(4, 2, 3), dtype=bool, numpy=
array([[[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])>

In [12]:
# Now lets see another case in general, FIT in number of weights
x_reshape = tf.constant([[3,5,6,6],
                         [4,6,-1,2]])

# THIS IS not the transpose as you see
tf.reshape(x_reshape, [4, 2])
tf.reshape(x_reshape, [4, -1])

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  5],
       [ 6,  6],
       [ 4,  6],
       [-1,  2]], dtype=int32)>

### tensorflow: Concatenation function.
This is a method that concatanates the tensors, without having to add a new axis.

In [13]:
# t1 and t2 tensors
t1 = [[1, 2, 3],
      [4, 5, 6]]

t2 = [[7, 8, 9],
      [10, 11, 12]]

# Lets see the shape of each of the tensors
print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

#Lets see the concatanetion across the rows
print(tf.concat([t1, t2], axis = 0))

#Lets see the concatanetion across the cols
print(tf.concat([t1, t2], axis = 1))


(2, 3)
(2, 3)
tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [14]:
# t1 and t2 tensors in 3D format
t1 = [[[1, 2, 3],
      [4, 5, 6]]]

t2 = [[[7, 8, 9],
      [10, 11, 12]]]

# Lets see the shape of each of the tensors
print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

#Lets see the concatanetion across axis zero, fixes 0 axis
print(tf.concat([t1, t2], axis = 0))


(1, 2, 3)
(1, 2, 3)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [15]:
#Lets see the concatanetion across axis zero, fixes 1 axis
print(tf.concat([t1, t2], axis = 1))

#It should be 1, 4, 3.

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]], shape=(1, 4, 3), dtype=int32)


In [16]:
#Lets see the concatanetion across axis zero, fixes 2 axis
print(tf.concat([t1, t2], axis = 2))

#It should be 1, 2, 6.

tf.Tensor(
[[[ 1  2  3  7  8  9]
  [ 4  5  6 10 11 12]]], shape=(1, 2, 6), dtype=int32)


In [17]:
### Concatanetion works like this
# We went from 1,2,3 - 1,2,3 -> 2,2,3 when axis = 0
# It goes from 1,2,3 - 1,2,3 -> 1,4,3 when axis = 1
# It goes from 1,2,3 - 1,2,3 -> 1,2,6 when axis = 2

###tensorflow: Stacking
This is another common method in tensorflow, adding a new axis to stack the tensors.

In [18]:
# t1 and t2 tensors
t1 = [[1, 2, 3],
      [4, 5, 6],
      [5, 6, 2],
      [1, 2, 1]]

t2 = [[7, 8, 9],
      [10, 11, 12],
      [0, 0, 2],
      [-1, 5, 2]]

# Print lets see the shape
print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

#This should create a new axis
tf.stack([t1, t2], axis = 0)

(4, 3)
(4, 3)


<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  2],
        [ 1,  2,  1]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 0,  0,  2],
        [-1,  5,  2]]], dtype=int32)>

In [19]:
# We went from 4,3 - 4,3 -> 2,4,3 when axis = 0
# It goes from 4,3 - 4,3 -> 4,2,3 when axis = 1
# It goes from 4,3 - 4,3 -> 4,3,2 when axis = 2
print(tf.stack([t1, t2], axis = 1))
print(tf.stack([t1, t2], axis = 2))

tf.Tensor(
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]

 [[ 5  6  2]
  [ 0  0  2]]

 [[ 1  2  1]
  [-1  5  2]]], shape=(4, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]

 [[ 5  0]
  [ 6  0]
  [ 2  2]]

 [[ 1 -1]
  [ 2  5]
  [ 1  2]]], shape=(4, 3, 2), dtype=int32)


In [20]:
# Lets emualte stack with concatanetion!
tf.concat([tf.expand_dims(t, axis = 0) for t in [t1, t2]], axis = 0)

#Expand dims function
# 4, 3 - 4,3 -> 1, 4, 3 - 1, 4, 3
#Concat function to new tensors
# 1, 4, 3 - 1, 4, 3 -> 2, 4, 3

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  2],
        [ 1,  2,  1]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 0,  0,  2],
        [-1,  5,  2]]], dtype=int32)>

### tensorflow padding

In [29]:
#Define tensor
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

#Define the paddings as the following:
# [1, 1] -> One row up and one row below
# [2, 2] -> Two columns left and right
# We can play with this to determine different paddings

paddings = tf.constant([[1, 1,], [2, 2]])
# 'constant_values' is 0.
# rank of 't' is 2.
tf.pad(t, paddings, "CONSTANT", constant_values = 0)

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

### tensorflow gathering

In [35]:
#Lets define a tensor named
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
params.shape
params[1:3+1]

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [33]:
tf.gather(params, [0, 5, 3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [39]:
#Lets do it for 2D
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
print(params.shape)
tf.gather(params, [0, 3], axis = 0)

(4, 3)


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.,  1.,  2.],
       [30., 31., 32.]], dtype=float32)>

In [43]:
tf.gather(params, [0, 2], axis = 1)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.,  2.],
       [10., 12.],
       [20., 22.],
       [30., 32.]], dtype=float32)>

In [55]:
#Lets do it for 3D
params = tf.constant([
                      [[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]],

                      [[3, 1, 5.0],
                      [1, 3, 10],
                      [0, 5, 32.0],
                      [0, 2, 4.0]]

                      ])
print(params.shape)
tf.gather(params, [0, 1], axis = 0)

(2, 4, 3)


<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [10., 11., 12.],
        [20., 21., 22.],
        [30., 31., 32.]],

       [[ 3.,  1.,  5.],
        [ 1.,  3., 10.],
        [ 0.,  5., 32.],
        [ 0.,  2.,  4.]]], dtype=float32)>

In [56]:
tf.gather(params, [2, 0], axis = 1)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[20., 21., 22.],
        [ 0.,  1.,  2.]],

       [[ 0.,  5., 32.],
        [ 3.,  1.,  5.]]], dtype=float32)>

### tensorflow: gather_nd

In [61]:
#Define the indices
indices=[[2, 1]]

#Define a parameters
params = [['a', 'b'],
          ['c', 'd'],
          ['e', 'f']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'f'], dtype=object)>

In [62]:
#Define the indices
indices=[2, 1]
tf.gather(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'e', b'f'],
       [b'c', b'd']], dtype=object)>

In [70]:
#Define the indices in 2D
indices=[[0, 0],
         [1, 0]]

#Define a parameters
params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]

print(tf.constant(params).shape)

#Making this method batch aware
print(tf.gather_nd(params, indices, batch_dims = 0))
print(tf.gather_nd(params, indices, batch_dims = 1))

(2, 2, 2)
tf.Tensor(
[[b'a0' b'b0']
 [b'a1' b'b1']], shape=(2, 2), dtype=string)
tf.Tensor([b'a0' b'c1'], shape=(2,), dtype=string)


In [72]:
#Define the indices in 3D
indices=[[[0, 1]],
         [[1, 0]],

         [[0, 0]],
         [[1, 1]]]

#Define a parameters
params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]

print(tf.constant(params).shape)

#Making this method batch aware
print(tf.gather_nd(params, indices, batch_dims = 0))
print(tf.gather_nd(params, indices, batch_dims = 1))

(2, 2, 2)
tf.Tensor(
[[[b'c0' b'd0']]

 [[b'a1' b'b1']]

 [[b'a0' b'b0']]

 [[b'c1' b'd1']]], shape=(4, 1, 2), dtype=string)


InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 8 values, but the requested shape has 4 [Op:Reshape] name: 