<a href="https://colab.research.google.com/github/juanpajedrez/tensorflow_learning/blob/main/Notebook_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensorflow: Variables
Here we will take a look into defining tensorflow variables to make them work.



In [1]:
# Import tensorflow as a module
import tensorflow as tf

In [2]:
# Create a tensorflow variable
x = tf.constant([1, 2])

In [3]:
# Create a variable
# trainable parameters allows for updating vars with gradients
x_var = tf.Variable(x, "var1")
print(x_var)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [4]:
# Lets do some subtraction across the variable
# THIS IS SAVED IN HISTORY
x_var.assign_add([5, 10])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 6, 12], dtype=int32)>

### Lets select a specific device and use it!

In [5]:
#Using a with statement, you can select specific device
with tf.device('CPU:0'):
  x_1 = tf.constant([1,3,4])
  x_2 = tf.constant([1])

with tf.device('GPU:0'):
  x_3 = tf.constant(x_1 + x_2)

#Lets take a look at the devices
print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device)

tf.Tensor([1 3 4], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2 4 5], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:GPU:0
