<a href="https://colab.research.google.com/github/juanpajedrez/tensorflow_learning/blob/main/Notebook_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Lets get the following here
import tensorflow as tf

### Tensorflow ragged tensors
Create tensors that have uneven number of elements

In [2]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])
print(tensor_two_d.shape)

(4, 3)


In [3]:
# Create a ragged tensor with different number of columns: n, d.
tensor_two_d = [[1,2,0],
                [3,],
                [1,5,6,5,6],
                [2,3]]
tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged.shape)

(4, None)


### tensorflow boolean mask
Pass a tensor list and pass a mask

In [4]:
  # Mask a 2D Tensor using specific mask indices
tf.ragged.boolean_mask(
    data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    mask=[[True, False, True], [False, False, False], [True, False, False]]).to_list()

[[1, 3], [], [7]]

### tensorflow ragged tensors: from row lengths
Take a look at the class method to generate a ragged tensor using from row lengths

In [5]:
print(tf.RaggedTensor.from_row_lengths(
    values = [3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths = [4, 0, 3, 1, 0]
))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


### tensorflow ragged tensors: from row limits
Take a look at the class method to generate a ragged tensor using row limits.

In [6]:
print(tf.RaggedTensor.from_row_limits(
    values = [3, 1, 4, 1, 5, 9, 2, 6],
    row_limits = [4, 4, 7, 8, 8]
))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


### tensorflow ragged tensors: from row splits
Take a look at the class method to generate a raggeed tensor using from row splits.

In [7]:
print(tf.RaggedTensor.from_row_splits(
    values = [3, 1, 4, 1, 5, 9, 2, 6],
    row_splits = [0, 4, 4, 7, 8, 8]
))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


### tensorflow ragged tensors: from Tensor
Take a look at using this class method to obtain a ragged tensor

In [8]:
#Example from the python docs
dt = tf.constant([
    [5, 7, 0],
    [0, 3, 0],
    [6, 0, 0]])

In [9]:
#Obtain the tf ragged tensor
tf.RaggedTensor.from_tensor(dt)

<tf.RaggedTensor [[5, 7, 0],
 [0, 3, 0],
 [6, 0, 0]]>

In [10]:
#Select specific lenghts
tf.RaggedTensor.from_tensor(dt, lengths=[1, 0, 3])

<tf.RaggedTensor [[5], [], [6, 0, 0]]>

### Tensorflow: Creating sparse Tensor
This is to deal with tensors that contains a lot of zeroes.

In [12]:
#Lets define a tensor_sparse object
tensor_sparse = tf.sparse.SparseTensor(
   indices = [[1,1], [3,4]], values =  [11, 56], dense_shape = [5,6]
)

In [13]:
#Lets print it
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [14]:
#Lets push it to dense
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

### Tensorflow: Tensors Strings

In [15]:
#Lets create a tensor string
tensor_string = tf.constant(["hello", "I am", "a string"])
print(tensor_string)

tf.Tensor([b'hello' b'I am' b'a string'], shape=(3,), dtype=string)


In [19]:
#Lets join all of them together
tf.strings.join(tensor_string, separator = "+")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello+I am+a string'>