<a href="https://colab.research.google.com/github/juanpajedrez/tensorflow_learning/blob/main/Notebook_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

### Basic Fundamentals to Create Boolean, String, and Zero_d Tensors

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string = tf.constant(["Hello world", "hi"])
print(tensor_string)

tf.Tensor([b'Hello world' b'hi'], shape=(2,), dtype=string)


### Converting numpy arrays to tensorflow tensors

In [ ]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


### tensorflow identity matrix creation

In [ ]:
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns=3,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns=5,
    batch_shape=[2,4],
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


### tensorflow fill method, zeros, ones, and ones_like


In [ ]:
fill_tensor = tf.fill([3, 4],\
  5, name = None
)

print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [ ]:
ones_tensor = tf.ones(
    [5, 3, 2],
    dtype = tf.dtypes.float32,
    name = None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [ ]:
ones_like_tensor = tf.ones_like(
    fill_tensor, dtype=None, name=None, layout=None
)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [ ]:
zeros_tensor = tf.zeros(
    [3, 2],
    dtype = tf.dtypes.float32,
    name = None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


### Tensorflow methods: shape, rank, size

In [ ]:
print(tf.shape(zeros_tensor, out_type = tf.int32))

tf.Tensor([3 2], shape=(2,), dtype=int32)


In [ ]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.rank(t)  # 3

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.size(t, out_type = tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

### Tensorflow creation random tensors: random normal, uniform


In [ ]:
random_normal_tensor = tf.random.normal(
    [3, 2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_normal_tensor)

tf.Tensor(
[[ 99.819695  99.04971 ]
 [ 99.96036   99.25746 ]
 [101.32315   99.381454]], shape=(3, 2), dtype=float32)


In [ ]:
random_uniform_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=1000,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_uniform_tensor)

tf.Tensor([701.70746   43.367863 560.4572   122.03384  279.9585  ], shape=(5,), dtype=float32)


### Create reproducible tensors using tf.random.set_seed()

In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=3, dtype=tf.int32, seed=10))


tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([1 0 0], shape=(3,), dtype=int32)


### Casting tensorflow arrays

In [ ]:
tensor_one_d = tf.constant([2,0.,-3,8,90], dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.int16)
casted_tensor_one_d_boolean = tf.cast(tensor_one_d, dtype=tf.bool)

print(tensor_one_d)
print(casted_tensor_one_d)
print(casted_tensor_one_d_boolean)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


### Creating 2D, 3D, and 4D tensorflow arrays

In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],
])

print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape)

(4, 2, 3)


In [ ]:
print(tensor_three_d.ndim)

3


In [ ]:
tensor_four_d = tf.constant([[
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],
],
[
    [[13,26,0],
    [3,5,-12]],

    [[10,2,0],
    [1,0,23]],

    [[5,8,0],
    [2,73,0]],

    [[2,1,9],
    [4,-30,32]],
],
[
    [[103,26,0],
    [3,50,-12]],

    [[100,2,0],
    [1,0,23]],

    [[5,28,0],
    [2,73,0]],

    [[22,1,9],
    [44,-320,32]],
],
                             ])

print(tensor_four_d)

tf.Tensor(
[[[[   1    2    0]
   [   3    5   -1]]

  [[  10    2    0]
   [   1    0    2]]

  [[   5    8    0]
   [   2    7    0]]

  [[   2    1    9]
   [   4   -3   32]]]


 [[[  13   26    0]
   [   3    5  -12]]

  [[  10    2    0]
   [   1    0   23]]

  [[   5    8    0]
   [   2   73    0]]

  [[   2    1    9]
   [   4  -30   32]]]


 [[[ 103   26    0]
   [   3   50  -12]]

  [[ 100    2    0]
   [   1    0   23]]

  [[   5   28    0]
   [   2   73    0]]

  [[  22    1    9]
   [  44 -320   32]]]], shape=(3, 4, 2, 3), dtype=int32)


### Tensors Indexing

Learning how to slice out tensors into respective indexes

In [ ]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])

# Go from min index to max index +1.
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:5+1])
print(tensor_indexed[1:6:2])
print(tensor_indexed[3:])
print(tensor_indexed[3:-2])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)
tf.Tensor([ 4  6 66  7], shape=(4,), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]]
)

#Index for the first three rows and two cols
print(tensor_two_d[ 0:3, 0:2])

#Index first three rows and all cols
print(tensor_two_d[0:3, :])

#Index the third row and second col to last
print(tensor_two_d[2, 1:])

#Index the first two rows and first column
print(tensor_two_d[1:3, 0])

# ... Picks all the rows for indexes
print(tensor_two_d[..., 1])


tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)
tf.Tensor([3 1], shape=(2,), dtype=int32)
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],
])

#Lets print the dimensions of the tensor.
print(tensor_three_d.shape)

#Index for the first 3D element
print(tensor_three_d[0, :, :])

#Index the first row of the first 3D element
print(tensor_three_d[0, 0, :])

#Index the last column of the first 3D element
print(tensor_three_d[0, :, -1])

#Index the last columns of the first and second 3D elements
print(tensor_three_d[0:2, ..., 2])

(4, 2, 3)
tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)
tf.Tensor([1 2 0], shape=(3,), dtype=int32)
tf.Tensor([ 0 -1], shape=(2,), dtype=int32)
tf.Tensor(
[[ 0 -1]
 [ 0  2]], shape=(2, 2), dtype=int32)
