<a href="https://colab.research.google.com/github/juanpajedrez/tensorflow_learning/blob/main/Notebook_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensorflow and mathematical operations

Here, we show the tf.math to use for mathematical operations.

In [2]:
import tensorflow as tf

In [3]:
# real number
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [4]:
tf.abs(tf.constant(-0.3))

<tf.Tensor: shape=(), dtype=float32, numpy=0.3>

In [5]:
# complex number
x_abs_complex = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [6]:
tf.sqrt((-2.25)**2 + (4.75)**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [7]:
x_1 = tf.constant([5,3,6,6,4,6], dtype = tf.float32)
x_2 = tf.constant([7,6,2,6,0,11], dtype = tf.float32)

#Add element wise, multiply, subtract, dividie
print(tf.add(x_1, x_2))
print(tf.subtract(x_1, x_2))
print(tf.multiply(x_1, x_2))
print(tf.divide(x_1, x_2))
print(tf.math.divide_no_nan(x_1, x_2, name=None))

tf.Tensor([12.  9.  8. 12.  4. 17.], shape=(6,), dtype=float32)
tf.Tensor([-2. -3.  4.  0.  4. -5.], shape=(6,), dtype=float32)
tf.Tensor([35. 18. 12. 36.  0. 66.], shape=(6,), dtype=float32)
tf.Tensor([0.71428573 0.5        3.         1.                inf 0.54545456], shape=(6,), dtype=float32)
tf.Tensor([0.71428573 0.5        3.         1.         0.         0.54545456], shape=(6,), dtype=float32)


### Broadcasting
Perform some mathematical operations to showcase the power of broadcasting

In [8]:
#1D tensors
x_1 = tf.constant([5,3,6,6,4,6], dtype = tf.float32)
x_2 = tf.constant([7], dtype = tf.float32)
x_2_stretched = tf.constant([7,7,7,7,7,7], dtype = tf.float32)

#Divide with only one value, and with stretched to show broadcasting.
print(tf.math.divide_no_nan(x_1, x_2, name=None))
print(tf.math.divide_no_nan(x_1, x_2_stretched, name = None))

tf.Tensor([0.71428573 0.42857143 0.85714287 0.85714287 0.5714286  0.85714287], shape=(6,), dtype=float32)
tf.Tensor([0.71428573 0.42857143 0.85714287 0.85714287 0.5714286  0.85714287], shape=(6,), dtype=float32)


In [9]:
#2D tensors
x_1 = tf.constant([[5,3,6,6,4,6]], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)

#Dimensions of length 1 would be stretched
print(x_1.shape)
print(x_2.shape)

#When multiplying, X_1 is stretched from (1,6)-> (3,6)
#X2 would be stretched from (3,1) -> (3,6)
print(tf.math.multiply(x_1, x_2, name=None))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


### Maximum, Minimum, argmax, and argmin

We are gonna see the usage of the max, min, argmax, and argmin methods.

In [10]:
#Maximum between two tensors
x = tf.constant([4., 2., -3., 2])
y = tf.constant([-2., 0., 2., 5.])

#Perform the maximum and minimum
print(tf.math.maximum(x, y))
print(tf.math.minimum(x, y))

tf.Tensor([4. 2. 2. 5.], shape=(4,), dtype=float32)
tf.Tensor([-2.  0. -3.  2.], shape=(4,), dtype=float32)


In [11]:
# Find the index where the max and min are using argmax and argmin
# For 1D tensors
x_argmax = tf.constant([200, 120, 130, 3, 6])
print(x_argmax)
print(tf.math.argmax(x_argmax))
print(tf.math.argmin(x_argmax))

x_argmax = tf.constant([200, 120, 1300, 3, 6])
print(x_argmax)
print(tf.math.argmax(x_argmax))
print(tf.math.argmin(x_argmax))

tf.Tensor([200 120 130   3   6], shape=(5,), dtype=int32)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor([ 200  120 1300    3    6], shape=(5,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)


In [12]:
# Find the index where the max and min are using argmax and argmin
# For 2D tensors
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]])
#Get the shape
print(x_argmax.shape)

#Specify axis 0 (rows)
print(tf.math.argmax(x_argmax, 0))
print(tf.math.argmin(x_argmax, 0))

#Specify to axis 1 (cols)
print(tf.math.argmax(x_argmax, 1))
print(tf.math.argmin(x_argmax, 1))

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [13]:
# Find the index where the max and min are using argmax and argmin
# For 3D tensors
x_argmax = tf.constant([[[2, 20, 30, 3, 6],
                         [5, 20, 10, 2, 3]],
                        [[3, 11, 16, 1, 8],
                         [5, 3, 2, 10, 20]],
                        [[14, 45, 23, 5, 27],
                         [10, 12, 4, 20, 2]]])

# Get the shape
print(x_argmax.shape)

#Specify axis 0 (Third dimension)
print(tf.math.argmax(x_argmax, 0))

#Specify to axis 1 (Second dimension)
print(tf.math.argmax(x_argmax, 1))

#Specify to axis 2 (Third dimension)
print(tf.math.argmax(x_argmax, 2))

(3, 2, 5)
tf.Tensor(
[[2 2 0 2 2]
 [2 0 0 2 1]], shape=(2, 5), dtype=int64)
tf.Tensor(
[[1 0 0 0 0]
 [1 0 0 1 1]
 [0 0 0 1 0]], shape=(3, 5), dtype=int64)
tf.Tensor(
[[2 1]
 [2 4]
 [1 3]], shape=(3, 2), dtype=int64)


### Power, reduce_sum, reduce_max, reduce_mean

Perform power and sum across a specific dimension

In [14]:
#Send the power
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[3, 0], [1, 4]])
tf.pow(x, y) #[[256, 65536], [9, 27]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]], dtype=int32)>

In [15]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [16]:
tensor_two_d = tf.constant([
    [1,-2,0],
    [3,5,100],
    [1,5,6],
    [2,3,8]
], dtype = tf.float16)

#Print the shape
print(tensor_two_d.shape)

#Pass the 2D tensor and reduce sum, max
print(tf.math.reduce_sum(
    tensor_two_d, axis=0, keepdims=False, name=None
))
print(tf.math.reduce_max(
    tensor_two_d, axis=0, keepdims=False, name=None
))
print(tf.math.reduce_mean(
    tensor_two_d, axis=0, keepdims=False, name=None
))

(4, 3)
tf.Tensor([  7.  11. 114.], shape=(3,), dtype=float16)
tf.Tensor([  3.   5. 100.], shape=(3,), dtype=float16)
tf.Tensor([ 1.75  2.75 28.5 ], shape=(3,), dtype=float16)


In [17]:
#Pass the 2D tensor and reduce sum, max
print(tf.math.reduce_sum(
    tensor_two_d, axis=1, keepdims=False, name=None
))
print(tf.math.reduce_max(
    tensor_two_d, axis=1, keepdims=False, name=None
))
print(tf.math.reduce_mean(
    tensor_two_d, axis=1, keepdims=False, name=None
))

tf.Tensor([ -1. 108.  12.  13.], shape=(4,), dtype=float16)
tf.Tensor([  1. 100.   6.   8.], shape=(4,), dtype=float16)
tf.Tensor([-0.3333 36.      4.      4.332 ], shape=(4,), dtype=float16)


### Top k values and Linear Algebra Operations

We are gonna take a look into some of the most common linear algebra operations, as well as the top k values function.

In [18]:
#First part are the values of top k values
#Second part are the indices
tf.math.top_k(tensor_two_d, k =2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[  1.,   0.],
       [100.,   5.],
       [  6.,   5.],
       [  8.,   3.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 2],
       [2, 1],
       [2, 1],
       [2, 1]], dtype=int32)>)

### 2D Tensors Linalg

In [19]:
#Lets define two matrices
X_1 = tf.constant([[1,2,0],
                  [3,5,-1]])
X_2 = tf.constant([[1,2,0, 2],
                  [3,5,-1, 2],
                  [4,5,6, 0]])
X_3 = tf.constant([[1,2,0, 2],
                  [3,5,-1, 2]])

#Print the shapes
print(X_1.shape)
print(X_2.shape)
print(X_3.shape)

tf.linalg.matmul(
    X_1,
    X_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    grad_a=False,
    grad_b=False,
    name=None
)

(2, 3)
(3, 4)
(2, 4)


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[  7,  12,  -2,   6],
       [ 14,  26, -11,  16]], dtype=int32)>

In [20]:
#Multiply X_3 and X_2 transposed
print(X_3@tf.transpose(X_2))

#Do it now with the linalg.matmul
tf.linalg.matmul(
    X_3,
    X_2,
    transpose_a=False,
    transpose_b=True,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    grad_a=False,
    grad_b=False,
    name=None
)

tf.Tensor(
[[ 9 17 14]
 [17 39 31]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 9, 17, 14],
       [17, 39, 31]], dtype=int32)>

In [21]:
#This is to enable certain numpy behavior
import tensorflow.experimental.numpy as tnp
tnp.experimental_enable_numpy_behavior()

### Get the transpose
print(X_1.T)
print(X_1@X_2)

tf.Tensor(
[[ 1  3]
 [ 2  5]
 [ 0 -1]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[  7  12  -2   6]
 [ 14  26 -11  16]], shape=(2, 4), dtype=int32)


In [22]:
#Transpose the matrix X_1 and X_2
tf.transpose(X_1)
tf.transpose(X_2)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  3,  4],
       [ 2,  5,  5],
       [ 0, -1,  6],
       [ 2,  2,  0]], dtype=int32)>

In [23]:
print(X_1)
print(X_2)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 1  2  0  2]
 [ 3  5 -1  2]
 [ 4  5  6  0]], shape=(3, 4), dtype=int32)


### 3D Tensors Linalg

In [33]:
#Create a two 3D matrices and perform bathc multiplication
X_1 = tf.constant([[[1,2],
                  [3,5,]],

                  [[10,0],
                  [1,2]],

                  [[5,8],
                  [2,7]],
])

X_2 = tf.constant([[[5,1,4],
                  [34,15,1]],

                  [[1,2,2],
                  [5,3,2]],

                  [[2,2,3],
                  [1,1,1]],
])

#Print the dimensions
print(X_1.shape)
print(X_2.shape)

print(tf.linalg.matmul(X_1, X_2))

(3, 2, 2)
(3, 2, 3)
tf.Tensor(
[[[ 73  31   6]
  [185  78  17]]

 [[ 10  20  20]
  [ 11   8   6]]

 [[ 18  18  23]
  [ 11  11  13]]], shape=(3, 2, 3), dtype=int32)


In [32]:
#Create a two 3D matrices
X_1 = tf.constant([[[10,0],
                    [1,2]]])

X_2 = tf.constant([[[1,2,2],
                    [5,3,2]]])

#Print the dimensions
print(X_1.shape)
print(X_2.shape)

print(tf.linalg.matmul(X_1, X_2))

(1, 2, 2)
(1, 2, 3)
tf.Tensor(
[[[10 20 20]
  [11  8  6]]], shape=(1, 2, 3), dtype=int32)


### Usage of linalg sparsity with matrices, and bandpart


In [35]:
#Lets define two sparse matrices
X_1 = tf.constant([[0, 0],
                  [0, 2]])
X_2 = tf.constant([[1,0,0],
                  [0,0,0]])

#Lets use the sparse argument to optimize its multiplications
print(tf.linalg.matmul(X_1, X_2, a_is_sparse=True, b_is_sparse=True))

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [43]:
#Lets define a 2D tensor
tensor_two_d = tf.constant([[1,-2, 0],
                  [3,5,100],
                  [1,5,6],
                  [2,3,8]], dtype = tf.float16)

#Lets find the band part conditioning on the position index
#### (m-n <= lower) && (n-m <= upper)

### m -- rows, n -- columns
# m-n matrix pos:[[0, -1, -2, -3]
#                [1, 0, -1, -2]
#                [2, 1, 0, -1]
#                [3, 2, 1, 0]],
# n-m matrix pos:[[ 0,  1,  2, 3]
#                [-1,  0,  1, 2]
#                [-2, -1,  0, 1]
#                [-3, -2, -1, 0]],

#Lets obtain the diagonal matrix
print(tf.linalg.band_part(tensor_two_d, 0, 0))

#Lets obtain the upper diagonal matrix
print(tf.linalg.band_part(tensor_two_d, 0, -1))

#Lets obtain the lower diagonal matrix
print(tf.linalg.band_part(tensor_two_d, -1, 0))

tf.Tensor(
[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 6.]
 [0. 0. 0.]], shape=(4, 3), dtype=float16)
tf.Tensor(
[[  1.  -2.   0.]
 [  0.   5. 100.]
 [  0.   0.   6.]
 [  0.   0.   0.]], shape=(4, 3), dtype=float16)
tf.Tensor(
[[1. 0. 0.]
 [3. 5. 0.]
 [1. 5. 6.]
 [2. 3. 8.]], shape=(4, 3), dtype=float16)
